name: lions_api
publish_to: "none"
environment:
  sdk: ^3.5.0

dependencies:
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  mysql_client: ^0.0.27 
  mailer: ^6.6.0
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^2.0.0